# Generated by Django 5.0.4 on 2024-05-15 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('health', models.IntegerField()),
                ('lasthealth', models.DateTimeField()),
                ('happiness', models.IntegerField()),
                ('lasthapiness', models.DateTimeField()),
                ('hunger', models.IntegerField()),
                ('lasthunger', models.DateTimeField()),
                ('energy', models.IntegerField()),
                ('lastenergy', models.DateTimeField()),
                ('shittiness', models.IntegerField()),
                ('lastshit', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('money', models.IntegerField()),
                ('lastjob', models.DateTimeField()),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
